Add contrib guide fixes #11
lansingcodes/organizer-resources pull request #14
Opened 2021-10-20 23:38 UTC by joeryan

Added contributors guide, fixes #11

2021-10-20 23:58 UTC, egillespie requested changes
This reads great! I only noticed one small issue: a link that doesn't seem to work. After that, let's ship this! 🤘

2021-10-20 23:58 UTC, egillespie commented on .github/CONTRIBUTING.md
> +to [customize your environment](#customizing-your-environment).
It looks like there's no section named "Customize Your Enironment". Would you mind removing this link and instead suggest they install the Required Software described below?

2021-10-21 01:22 UTC, joeryan commented on .github/CONTRIBUTING.md
> +to [customize your environment](#customizing-your-environment).
Thanks, missed that one.

2021-10-21 02:10 UTC, egillespie approved these changes
Love the double call-out of important sections. Nice touch! 👏  :shipit:

2021-10-21 02:10 UTC, merged